#!/bin/bash
echo "Install Docker-ce using the apt repository methode"
echo "Set up Docker's apt repository."
echo " Add Docker's official GPG key:"
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

echo "# Add the repository to Apt sources:"
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

Blue='\033[0;34m'   #'0;34' is Blue's ANSI color code
echo -e "STARTS ${Blue}installing-Docker-ce,cli,io-and-compose-plugin${NOCOLOR} on your VM"
#echo -e "${NOCOLOR}"
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

echo "Verify that the Docker Engine installation"
sudo docker run hello-world
echo "When the container runs, it prints a confirmation message and exit"

echo "Docker and Docker compose Version"
sudo docker -v && docker compose version
